#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none
#  datasource:
#    url: jdbc:mysql://localhost:3306/bot_titles?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root

scheduler:
  enabled : ${scheduler_enabled:false}

telegram:
  bot:
    token: 1043763747:AAF6Kfcf0CB_lmUleMvGvPs8ZF9K1d2IW6k
    name: ZaharTouristBot

server:
  port: 8080



feign:
  client:
    config:
      titles:
        url: https://ani-title.site/
        connectTimeout: 5000
        readTimeout: 15000
        loggerLevel: FULL
  httpclient:
    enabled: true
    max-connections: 50
    max-connections-per-route: 50
    time-to-live: 900
    time-to-live-unit: SECONDS
