spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/bot_titles?useSSL=false&serverTimezone=UTC
    username: root
    password: root

scheduler:
  enabled : false

telegram:
  bot:
    token: 1043763747:AAF6Kfcf0CB_lmUleMvGvPs8ZF9K1d2IW6k
    name: ZaharTouristBot

server:
  port: 8080
